-- VoteYadi initial Supabase schema.
-- Run this file once in Supabase Dashboard -> SQL Editor.

create extension if not exists pg_trgm with schema extensions;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.villages (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint villages_name_not_blank check (length(btrim(name)) > 0),
  constraint villages_slug_not_blank check (length(btrim(slug)) > 0)
);

create unique index if not exists villages_name_lower_uidx
  on public.villages (lower(name));
create unique index if not exists villages_slug_lower_uidx
  on public.villages (lower(slug));

drop trigger if exists villages_set_updated_at on public.villages;
create trigger villages_set_updated_at
before update on public.villages
for each row execute function public.set_updated_at();

create table if not exists public.documents (
  id uuid primary key default gen_random_uuid(),
  village_id uuid not null references public.villages(id) on delete cascade,
  original_filename text not null,
  r2_key text not null unique,
  r2_etag text,
  sha256 text,
  size_bytes bigint not null default 0,
  page_count integer not null default 0,
  status text not null default 'uploaded',
  error_message text,
  record_count integer not null default 0,
  ocr_page_count integer not null default 0,
  version integer not null default 1,
  active boolean not null default false,
  uploaded_at timestamptz not null default now(),
  processing_started_at timestamptz,
  indexed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint documents_filename_not_blank check (length(btrim(original_filename)) > 0),
  constraint documents_r2_key_not_blank check (length(btrim(r2_key)) > 0),
  constraint documents_size_nonnegative check (size_bytes >= 0),
  constraint documents_page_count_nonnegative check (page_count >= 0),
  constraint documents_record_count_nonnegative check (record_count >= 0),
  constraint documents_ocr_page_count_nonnegative check (ocr_page_count >= 0),
  constraint documents_version_positive check (version > 0),
  constraint documents_status_valid check (
    status in ('uploaded', 'queued', 'processing', 'ready', 'failed', 'deleting')
  )
);

create index if not exists documents_village_idx
  on public.documents (village_id);
create index if not exists documents_status_idx
  on public.documents (status);
create index if not exists documents_village_active_idx
  on public.documents (village_id, active)
  where active = true;

drop trigger if exists documents_set_updated_at on public.documents;
create trigger documents_set_updated_at
before update on public.documents
for each row execute function public.set_updated_at();

create table if not exists public.voters (
  id bigint generated by default as identity primary key,
  document_id uuid not null references public.documents(id) on delete cascade,
  village_id uuid not null references public.villages(id) on delete cascade,
  record_index integer not null,
  name text not null,
  name_normalized text not null default '',
  name_latin text not null default '',
  relation_name text not null default '',
  relation_name_normalized text not null default '',
  relation_type text not null default '',
  epic text not null default '',
  serial text not null default '',
  house text not null default '',
  age integer,
  gender text not null default '',
  part text not null default '',
  section text not null default '',
  page integer not null default 1,
  script text not null default '',
  raw_ocr_text text,
  ocr_confidence real,
  created_at timestamptz not null default now(),
  constraint voters_record_index_nonnegative check (record_index >= 0),
  constraint voters_name_not_blank check (length(btrim(name)) > 0),
  constraint voters_age_valid check (age is null or age between 0 and 130),
  constraint voters_page_positive check (page > 0),
  constraint voters_ocr_confidence_valid check (
    ocr_confidence is null or ocr_confidence between 0 and 100
  ),
  constraint voters_document_record_unique unique (document_id, record_index)
);

create index if not exists voters_village_idx
  on public.voters (village_id);
create index if not exists voters_document_idx
  on public.voters (document_id);
create index if not exists voters_epic_upper_idx
  on public.voters (upper(epic))
  where epic <> '';
create index if not exists voters_village_serial_idx
  on public.voters (village_id, serial)
  where serial <> '';
create index if not exists voters_village_part_idx
  on public.voters (village_id, part)
  where part <> '';
create index if not exists voters_name_normalized_trgm_idx
  on public.voters using gin (name_normalized extensions.gin_trgm_ops);
create index if not exists voters_name_latin_trgm_idx
  on public.voters using gin (name_latin extensions.gin_trgm_ops);
create index if not exists voters_relation_normalized_trgm_idx
  on public.voters using gin (relation_name_normalized extensions.gin_trgm_ops);

create table if not exists public.processing_jobs (
  id uuid primary key default gen_random_uuid(),
  document_id uuid not null references public.documents(id) on delete cascade,
  status text not null default 'queued',
  attempt integer not null default 0,
  progress integer not null default 0,
  pages_processed integer not null default 0,
  total_pages integer not null default 0,
  error_message text,
  cloud_run_execution text,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint processing_jobs_status_valid check (
    status in ('queued', 'running', 'succeeded', 'failed', 'cancelled')
  ),
  constraint processing_jobs_attempt_nonnegative check (attempt >= 0),
  constraint processing_jobs_progress_valid check (progress between 0 and 100),
  constraint processing_jobs_pages_processed_nonnegative check (pages_processed >= 0),
  constraint processing_jobs_total_pages_nonnegative check (total_pages >= 0)
);

create index if not exists processing_jobs_document_idx
  on public.processing_jobs (document_id, created_at desc);
create index if not exists processing_jobs_status_idx
  on public.processing_jobs (status);

drop trigger if exists processing_jobs_set_updated_at on public.processing_jobs;
create trigger processing_jobs_set_updated_at
before update on public.processing_jobs
for each row execute function public.set_updated_at();

-- Only user IDs listed here are administrators. Supabase Auth owns the
-- corresponding account in auth.users.
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

-- Lock all application data by default. The Cloud Run API will use the
-- server-side service-role key. That key must never be placed in Flutter.
alter table public.villages enable row level security;
alter table public.documents enable row level security;
alter table public.voters enable row level security;
alter table public.processing_jobs enable row level security;
alter table public.admin_users enable row level security;

drop policy if exists admin_users_can_read_self on public.admin_users;
create policy admin_users_can_read_self
on public.admin_users
for select
to authenticated
using (user_id = auth.uid());

comment on table public.villages is 'Village catalogue shown in VoteYadi.';
comment on table public.documents is 'R2 PDF objects and their OCR/indexing state.';
comment on table public.voters is 'Parsed voter records; PDFs remain the source of truth.';
comment on table public.processing_jobs is 'Cloud Run OCR job status and retry history.';
comment on table public.admin_users is 'Supabase Auth users allowed to administer VoteYadi.';
